const fs = require('fs');
const path = require('path');

// --- Isometric Utility Functions ---

function isoX(x, y) {
    return (x - y) * Math.cos(Math.PI / 6);
}

function isoY(x, y) {
    return (x + y) * Math.sin(Math.PI / 6);
}

function toIso(x, y, z) {
    const screenX = (x - y) * 0.866; // cos(30)
    const screenY = (x + y) * 0.5 - z; // sin(30)
    return { x: 400 + screenX, y: 300 + screenY }; // Center roughly at 400,300
}

function drawCube(x, y, z, size, colorTop, colorLeft, colorRight, label) {
    const center = toIso(x, y, z);
    const top = toIso(x, y, z + size);
    const bottom = toIso(x, y, z);

    // Vertices relative to center (sort of)
    // Actually, let's just do face by face

    // We need 8 corners
    const p1 = toIso(x, y, z + size);
    const p2 = toIso(x + size, y, z + size);
    const p3 = toIso(x + size, y + size, z + size);
    const p4 = toIso(x, y + size, z + size);

    const p5 = toIso(x, y, z);
    const p6 = toIso(x + size, y, z);
    const p7 = toIso(x + size, y + size, z);
    const p8 = toIso(x, y + size, z);

    let svg = '';

    // Top Face (p1-p2-p3-p4)
    svg += `<path d="M${p1.x},${p1.y} L${p2.x},${p2.y} L${p3.x},${p3.y} L${p4.x},${p4.y} Z" fill="${colorTop}" stroke="white" stroke-width="1"/>`;

    // Right Face (p2-p3-p7-p6)
    svg += `<path d="M${p2.x},${p2.y} L${p3.x},${p3.y} L${p7.x},${p7.y} L${p6.x},${p6.y} Z" fill="${colorRight}" stroke="white" stroke-width="1"/>`;

    // Left Face (p1-p4-p8-p5)
    svg += `<path d="M${p1.x},${p1.y} L${p4.x},${p4.y} L${p8.x},${p8.y} L${p5.x},${p5.y} Z" fill="${colorLeft}" stroke="white" stroke-width="1"/>`;

    // Label
    if (label) {
        // Simple positioning
        svg += `<text x="${top.x}" y="${top.y - 20}" text-anchor="middle" fill="#333" font-family="Arial" font-weight="bold" font-size="14">${label}</text>`;
    }

    return svg;
}

function drawPipe(x1, y1, z1, x2, y2, z2, color) {
    const start = toIso(x1, y1, z1);
    const end = toIso(x2, y2, z2);
    return `<line x1="${start.x}" y1="${start.y}" x2="${end.x}" y2="${end.y}" stroke="${color}" stroke-width="6" stroke-linecap="round" />`;
}

function drawArrowForPipe(x1, y1, z1, x2, y2, z2) {
    const start = toIso(x1, y1, z1);
    const end = toIso(x2, y2, z2);
    const midX = (start.x + end.x) / 2;
    const midY = (start.y + end.y) / 2;
    return `<circle cx="${midX}" cy="${midY}" r="4" fill="white"/>`;
}

function createSVG(content, title) {
    return `<svg width="800" height="1200" viewBox="0 0 800 1200" xmlns="http://www.w3.org/2000/svg">
    <defs>
        <linearGradient id="bgParams" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" style="stop-color:#e0f7fa;stop-opacity:1" />
            <stop offset="100%" style="stop-color:#b2ebf2;stop-opacity:1" />
        </linearGradient>
    </defs>
    <rect width="800" height="1200" fill="url(#bgParams)"/>
    <text x="400" y="80" text-anchor="middle" font-family="Microsoft YaHei" font-size="32" font-weight="bold" fill="#006064">${title}</text>
    <g transform="translate(0, 200) scale(1.0)">
    ${content}
    </g>
    <!-- Decoration -->
    <text x="400" y="1150" text-anchor="middle" font-family="Arial" font-size="12" fill="#888">Generated by Gemini Agent</text>
    </svg>`;
}

// --- Diagrams ---

// 1. Power to Methane: Elec - Gas - Heat
function genMethane() {
    let s = '';
    // Wind/Solar
    s += drawCube(0, 0, 0, 60, "#a5d6a7", "#81c784", "#66bb6a", "Renewables (Wind/Solar)");

    // Electrolyzer
    s += drawPipe(60, 30, 0, 150, 30, 0, "#fdd835"); // Elec connection
    s += drawCube(150, 0, 0, 60, "#4dd0e1", "#26c6da", "#00bcd4", "Electrolysis (H2)");

    // CO2
    s += drawCube(150, 150, 0, 40, "#bdbdbd", "#9e9e9e", "#757575", "CO2 Capture");
    s += drawPipe(170, 150, 20, 170, 60, 20, "#9e9e9e"); // CO2 pipe

    // Methanation Reactor
    s += drawPipe(210, 30, 20, 300, 30, 20, "#e1bee7"); // H2 pipe
    s += drawCube(300, 0, 0, 70, "#ffcc80", "#ffb74d", "#ffa726", "Methanation");

    // Output 1: Methane Gas Grid
    s += drawPipe(370, 35, 20, 450, 35, 20, "#8d6e63");
    s += drawCube(450, 10, 0, 50, "#8d6e63", "#795548", "#6d4c41", "Gas Grid (CH4)");

    // Output 2: Heat Grid
    s += drawPipe(370, 20, 50, 450, -50, 50, "#ffab91");
    s += drawCube(450, -80, 0, 50, "#ffab91", "#ff8a65", "#ff7043", "Distict Heating");

    return createSVG(s, "Power to Methane (电-气-热三网耦合)");
}

// 2. Power to Methanol: H2 + CO2 -> Methanol -> MTO -> Olefins
function genMethanol() {
    let s = '';
    s += drawCube(0, 0, 0, 60, "#a5d6a7", "#81c784", "#66bb6a", "Green Power");

    s += drawPipe(60, 30, 20, 150, 30, 20, "#fdd835");
    s += drawCube(150, 0, 0, 60, "#4dd0e1", "#26c6da", "#00bcd4", "Electrolysis");

    s += drawCube(150, 150, 0, 40, "#bdbdbd", "#9e9e9e", "#757575", "CO2 Source");
    s += drawPipe(170, 150, 20, 300, 60, 20, "#9e9e9e"); // CO2 pipe long

    s += drawPipe(210, 30, 30, 300, 30, 30, "#e1bee7"); // H2 pipe
    s += drawCube(300, 0, 0, 60, "#ba68c8", "#ab47bc", "#9c27b0", "Methanol Synthesis");

    s += drawPipe(360, 30, 30, 450, 30, 30, "#ad1457");
    s += drawCube(450, 0, 0, 60, "#ec407a", "#d81b60", "#c2185b", "MTO Unit");

    s += drawPipe(510, 30, 30, 580, 30, 30, "#880e4f");
    s += drawCube(580, 10, 0, 40, "#fff59d", "#fff176", "#ffee58", "Green Olefins");

    return createSVG(s, "Power to Methanol (绿色烯烃)");
}

// 3. Power to Liquid: H2 + CO2 -> FT -> Kerosene
function genLiquid() {
    let s = '';
    s += drawCube(0, 0, 0, 60, "#a5d6a7", "#81c784", "#66bb6a", "Green Power");

    s += drawPipe(60, 30, 20, 150, 30, 20, "#fdd835");
    s += drawCube(150, 0, 0, 60, "#4dd0e1", "#26c6da", "#00bcd4", "Electrolysis");

    s += drawCube(150, 150, 0, 40, "#bdbdbd", "#9e9e9e", "#757575", "CO2 Capture");
    s += drawPipe(170, 150, 20, 300, 60, 20, "#9e9e9e");

    s += drawPipe(210, 30, 30, 300, 30, 30, "#e1bee7");
    s += drawCube(300, 0, 0, 60, "#90a4ae", "#78909c", "#607d8b", "Fischer-Tropsch");

    s += drawPipe(360, 30, 30, 450, 30, 30, "#263238");
    s += drawCube(450, 0, 0, 60, "#0277bd", "#01579b", "#014377", "Refining");

    s += drawPipe(510, 30, 30, 580, 30, 30, "#29b6f6");
    s += drawCube(580, 10, 0, 40, "#b3e5fc", "#81d4fa", "#4fc3f7", "Green Kerosene");

    return createSVG(s, "Power to Liquid (绿色航煤)");
}

// 4. Power to H2 to Power: Salt Cavern -> Turbine
function genH2Power() {
    let s = '';
    s += drawCube(0, 0, 0, 60, "#a5d6a7", "#81c784", "#66bb6a", "Green Power");

    s += drawPipe(60, 30, 20, 150, 30, 20, "#fdd835");
    s += drawCube(150, 0, 0, 60, "#4dd0e1", "#26c6da", "#00bcd4", "Electrolysis");

    // Salt Cavern (Underground)
    s += drawPipe(180, 60, 0, 180, 200, -50, "#e1bee7"); // Down to cavern
    s += drawCube(150, 200, -50, 80, "#e1bee7", "#ce93d8", "#ba68c8", "Salt Cavern Storage");

    // Back to Power
    s += drawPipe(230, 200, -30, 350, 60, 0, "#e1bee7"); // Up to turbine
    s += drawCube(350, 0, 0, 70, "#ff7043", "#f4511e", "#e64a19", "H2 Gas Turbine");

    s += drawPipe(420, 35, 20, 500, 35, 20, "#ffeb3b");
    s += drawCube(500, 0, 0, 60, "#ffeb3b", "#fdd835", "#fbc02d", "Power Grid");

    return createSVG(s, "Power to H2 to Power (跨季节储能)");
}

// Write files
const dir = path.join(__dirname, 'assets');
if (!fs.existsSync(dir)) fs.mkdirSync(dir);

fs.writeFileSync(path.join(dir, 'bg_methane.svg'), genMethane());
fs.writeFileSync(path.join(dir, 'bg_methanol.svg'), genMethanol());
fs.writeFileSync(path.join(dir, 'bg_liquid.svg'), genLiquid());
fs.writeFileSync(path.join(dir, 'bg_h2power.svg'), genH2Power());

console.log("SVG diagrams generated successfully.");
